const sizeOptions = (baseWeight) => [
  {
    id: "standard",
    label: "Стандарт",
    weight: baseWeight,
    priceDelta: 0,
  },
  {
    id: "large",
    label: "Большая",
    weight: baseWeight + 100,
    priceDelta: 45,
  },
  {
    id: "family",
    label: "Семейная",
    weight: baseWeight + 220,
    priceDelta: 85,
  },
];

const extraOptions = [
  {
    id: "none",
    label: "Без добавок",
    description: "Классическая подача",
    priceDelta: 0,
  },
  {
    id: "cheese",
    label: "Больше сыра",
    description: "Дополнительная порция сыра",
    priceDelta: 25,
  },
  {
    id: "sauce",
    label: "Фирменный соус",
    description: "Порция фирменного соуса SimpleFood",
    priceDelta: 15,
  },
];

const createProduct = ({
  id,
  category,
  title,
  description,
  image,
  alt,
  price,
  weight,
}) => ({
  id,
  category,
  title,
  description,
  image,
  alt,
  price,
  weight,
  parameters: {
    sizes: sizeOptions(weight),
    extras: extraOptions.map((option) => ({ ...option })),
  },
});

export const categories = [
  { id: "burgers", label: "Бургеры" },
  { id: "pizza", label: "Пицца" },
  { id: "sandwiches", label: "Сэндвичи" },
  { id: "asian", label: "Азиатская кухня" },
  { id: "drinks", label: "Напитки" },
];

export const products = [
  createProduct({
    id: "cheeseburger-salad",
    category: "burgers",
    title: "Чизбургер с салатом",
    description: "Сочная говяжья котлета, сыр чеддер, свежий салат и фирменный соус.",
    image: "assets/images/products/cheeseburger.jpg",
    alt: "Чизбургер с листьями салата",
    price: 160,
    weight: 280,
  }),
  createProduct({
    id: "beef-burger",
    category: "burgers",
    title: "Бифбургер",
    description: "Говяжья котлета на гриле, томаты, маринованный лук и горчичный соус.",
    image: "assets/images/products/beef-burger.jpg",
    alt: "Бифбургер с говяжьей котлетой",
    price: 190,
    weight: 310,
  }),
  createProduct({
    id: "royal-cheeseburger",
    category: "burgers",
    title: "Королевский чизбургер",
    description: "Две котлеты, двойная порция сыра, хрустящие огурцы и соус барбекю.",
    image: "assets/images/products/royal-burger.jpg",
    alt: "Королевский чизбургер",
    price: 260,
    weight: 390,
  }),
  createProduct({
    id: "black-burger",
    category: "burgers",
    title: "Чёрный гамбургер",
    description: "Пряная булочка, говяжья котлета, карамелизированный лук и сыр.",
    image: "assets/images/products/black-burger.jpg",
    alt: "Чёрный гамбургер",
    price: 199,
    weight: 300,
  }),
  createProduct({
    id: "chicken-burger",
    category: "burgers",
    title: "Чикен бургер",
    description: "Хрустящее куриное филе, салат, томаты и нежный сливочный соус.",
    image: "assets/images/products/chicken-burger.jpg",
    alt: "Бургер с куриной котлетой",
    price: 180,
    weight: 270,
  }),
  createProduct({
    id: "bbq-burger",
    category: "burgers",
    title: "Бургер BBQ",
    description: "Котлета на гриле, копчёный бекон, сыр, луковые кольца и соус BBQ.",
    image: "assets/images/products/beef-burger.jpg",
    alt: "Бургер барбекю с беконом",
    price: 230,
    weight: 350,
  }),
  createProduct({
    id: "spicy-burger",
    category: "burgers",
    title: "Острый бургер",
    description: "Говяжья котлета, перец халапеньо, сыр и пикантный томатный соус.",
    image: "assets/images/products/black-burger.jpg",
    alt: "Острый бургер с перцем",
    price: 220,
    weight: 320,
  }),
  createProduct({
    id: "vegetable-burger",
    category: "burgers",
    title: "Овощной бургер",
    description: "Овощная котлета, свежий салат, томаты, огурцы и соус с зеленью.",
    image: "assets/images/products/cheeseburger.jpg",
    alt: "Овощной бургер",
    price: 170,
    weight: 260,
  }),
  createProduct({
    id: "pepperoni-pizza",
    category: "pizza",
    title: "Пепперони",
    description: "Томатный соус, моцарелла и пикантная пепперони на тонком тесте.",
    image: "assets/images/restaurants/blaze-pizza.jpg",
    alt: "Пицца пепперони",
    price: 240,
    weight: 430,
  }),
  createProduct({
    id: "mushroom-pizza",
    category: "pizza",
    title: "Грибная пицца",
    description: "Шампиньоны, сливочный соус, моцарелла и ароматные травы.",
    image: "assets/images/restaurants/pizza-hut.jpg",
    alt: "Пицца с грибами",
    price: 235,
    weight: 450,
  }),
  createProduct({
    id: "rancho-pizza",
    category: "pizza",
    title: "Пицца Ранчо",
    description: "Курица, колбаски, сладкий перец, сыр и фирменный соус ранч.",
    image: "assets/images/restaurants/rancho-pizza.jpg",
    alt: "Пицца с курицей и колбасками",
    price: 270,
    weight: 480,
  }),
  createProduct({
    id: "cheese-pizza",
    category: "pizza",
    title: "Четыре сыра",
    description: "Моцарелла, дорблю, пармезан и чеддер на сливочной основе.",
    image: "assets/images/restaurants/blaze-pizza.jpg",
    alt: "Пицца четыре сыра",
    price: 280,
    weight: 420,
  }),
  createProduct({
    id: "club-sandwich",
    category: "sandwiches",
    title: "Клаб-сэндвич",
    description: "Куриное филе, бекон, томаты, салат и соус между тостами.",
    image: "assets/images/products/chicken-burger.jpg",
    alt: "Клаб-сэндвич с курицей",
    price: 155,
    weight: 240,
  }),
  createProduct({
    id: "beef-sandwich",
    category: "sandwiches",
    title: "Сэндвич с говядиной",
    description: "Ростбиф, сыр, свежие овощи и горчичный соус.",
    image: "assets/images/products/beef-burger.jpg",
    alt: "Сэндвич с говядиной",
    price: 175,
    weight: 250,
  }),
  createProduct({
    id: "cheese-sandwich",
    category: "sandwiches",
    title: "Сырный сэндвич",
    description: "Три вида сыра, томаты и соус песто в хрустящем хлебе.",
    image: "assets/images/products/cheeseburger.jpg",
    alt: "Сэндвич с сыром и томатами",
    price: 145,
    weight: 220,
  }),
  createProduct({
    id: "chicken-sandwich",
    category: "sandwiches",
    title: "Чикен-сэндвич",
    description: "Курица гриль, огурцы, салат и нежный йогуртовый соус.",
    image: "assets/images/products/chicken-burger.jpg",
    alt: "Сэндвич с курицей гриль",
    price: 165,
    weight: 245,
  }),
  createProduct({
    id: "teriyaki-chicken",
    category: "asian",
    title: "Курица терияки",
    description: "Куриное филе, рис, овощи и густой соус терияки.",
    image: "assets/images/restaurants/kfc.jpg",
    alt: "Курица терияки с рисом",
    price: 210,
    weight: 350,
  }),
  createProduct({
    id: "beef-noodles",
    category: "asian",
    title: "Лапша с говядиной",
    description: "Пшеничная лапша, говядина, овощи и кунжутный соус.",
    image: "assets/images/restaurants/mcdonalds.jpg",
    alt: "Лапша с говядиной и овощами",
    price: 225,
    weight: 360,
  }),
  createProduct({
    id: "vegetable-rice",
    category: "asian",
    title: "Рис с овощами",
    description: "Жареный рис, сезонные овощи, яйцо и соевый соус.",
    image: "assets/images/restaurants/star-burgers.jpg",
    alt: "Жареный рис с овощами",
    price: 175,
    weight: 330,
  }),
  createProduct({
    id: "spicy-chicken",
    category: "asian",
    title: "Острая курица",
    description: "Курица в пряном соусе, овощи, рис и свежая зелень.",
    image: "assets/images/restaurants/kfc.jpg",
    alt: "Острая курица с рисом",
    price: 215,
    weight: 345,
  }),
  createProduct({
    id: "orange-lemonade",
    category: "drinks",
    title: "Апельсиновый лимонад",
    description: "Апельсин, лимон, мята и газированная вода.",
    image: "assets/images/products/orange-lemonade.svg",
    alt: "Апельсиновый лимонад со льдом",
    price: 75,
    weight: 350,
  }),
  createProduct({
    id: "berry-drink",
    category: "drinks",
    title: "Ягодный морс",
    description: "Клюква, смородина и малина без искусственных добавок.",
    image: "assets/images/products/berry-drink.svg",
    alt: "Ягодный напиток",
    price: 65,
    weight: 350,
  }),
  createProduct({
    id: "iced-tea",
    category: "drinks",
    title: "Холодный чай",
    description: "Чёрный чай, лимон, персик и кубики льда.",
    image: "assets/images/products/iced-tea.svg",
    alt: "Холодный чай с лимоном",
    price: 70,
    weight: 400,
  }),
  createProduct({
    id: "coffee-drink",
    category: "drinks",
    title: "Кофе с молоком",
    description: "Ароматный эспрессо с тёплым молоком и нежной пеной.",
    image: "assets/images/products/coffee-drink.svg",
    alt: "Кофе с молочной пеной",
    price: 80,
    weight: 300,
  }),
];

export const getProductById = (id) =>
  products.find((product) => product.id === id);
